version: '3.6'
services:
  # service backend node
  4t_search_engine:
    container_name: 4t_search_engine
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=12345678
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - esnet

  # service elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      # - xpack.security.enabled=true
    networks:
      - esnet

  # service kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD=12345678
      # - xpack.security.enabled=true
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - esnet

volumes:
  esdata:

networks:
  esnet:
    driver: bridge
